# Generated by Django 2.0.1 on 2019-08-17 23:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('listings', '0001_initial'), ('listings', '0002_auto_20190816_2300'), ('listings', '0003_auto_20190816_2303'), ('listings', '0004_listing_zipcode'), ('listings', '0005_auto_20190817_1656'), ('listings', '0006_auto_20190817_1657'), ('listings', '0007_auto_20190817_1658')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
    
    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='postcode',
            new_name='zipcode',
        ),
    ]
    
