# Generated by Django 2.0.1 on 2019-08-18 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('square_feet', models.IntegerField()),
                ('main_img', models.ImageField(upload_to='main/%Y/%m/%d/')),
                ('img_1', models.ImageField(blank=True, upload_to='others/%Y/%m/%d/')),
                ('img_2', models.ImageField(blank=True, upload_to='others/%Y/%m/%d/')),
                ('img_3', models.ImageField(blank=True, upload_to='others/%Y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='others/%Y/%m/%d/')),
                ('img_5', models.ImageField(blank=True, upload_to='others/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('paid_fee', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
