# Generated by Django 2.2.4 on 2019-08-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190816_2300'),
    ]
