# Generated by Django 2.2.4 on 2019-08-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190816_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
