# Generated by Django 2.0.1 on 2019-08-17 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_auto_20190817_1656'), ('accounts', '0003_auto_20190817_1657'), ('accounts', '0004_auto_20190817_1658')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='UserProfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
