# Generated by Django 2.0.13 on 2019-08-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='UserProfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
