# Generated by Django 2.0.13 on 2019-08-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190817_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='UserProfile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
