# Generated by Django 2.0.13 on 2019-08-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190817_1657'),
    ]


