# Generated by Django 2.0.13 on 2019-08-21 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='General message', max_length=50)),
                ('your_name', models.CharField(default='Admin', max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('posted', models.DateTimeField(default=datetime.datetime.now)),
                ('new_message', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyEnquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100)),
                ('to_id', models.IntegerField(default=1)),
                ('to_email', models.EmailField(max_length=100)),
                ('house_id', models.IntegerField(default=1)),
                ('house_name', models.CharField(max_length=100)),
                ('viewing', models.BooleanField(default=False)),
                ('message', models.TextField(max_length=2000)),
                ('posted', models.DateTimeField(default=datetime.datetime.now)),
                ('sender', models.CharField(max_length=100)),
                ('sender_id', models.IntegerField(default=1)),
                ('sender_email', models.EmailField(max_length=100)),
                ('new_to', models.BooleanField(default=True)),
                ('delete_to', models.BooleanField(default=False)),
                ('new_sender', models.BooleanField(default=False)),
                ('delete_sender', models.BooleanField(default=False)),
            ],
        ),
    ]
