# Generated by Django 2.0.13 on 2019-08-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20190817_1657'),
        ('products', '0002_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
