# Generated by Django 2.0.13 on 2019-08-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20190817_1658'),
        ('products', '0003_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
